-- Database schema for commesse tracking (Supabase/Postgres)
-- Note: uses enums and basic constraints; adjust as needed.

-- Extensions
create extension if not exists pgcrypto;
create extension if not exists pg_trgm;

-- Enums
do $$
begin
  if not exists (select 1 from pg_type where typname = 'commessa_stato') then
    create type commessa_stato as enum ('nuova', 'in_corso', 'chiusa', 'sospesa');
  end if;
  if not exists (select 1 from pg_type where typname = 'reparto_stato') then
    create type reparto_stato as enum ('da_fare', 'in_corso', 'fatto');
  end if;
  if not exists (select 1 from pg_type where typname = 'ruolo_utente') then
    create type ruolo_utente as enum ('admin', 'responsabile', 'planner', 'operatore', 'viewer');
  end if;
  if not exists (select 1 from pg_type where typname = 'ruolo_assegnazione') then
    create type ruolo_assegnazione as enum ('owner', 'collaboratore');
  end if;
  if not exists (select 1 from pg_type where typname = 'attivita_stato') then
    create type attivita_stato as enum ('pianificata', 'in_corso', 'completata', 'annullata', 'non_necessaria');
  end if;
end $$;

-- Helper function for updated_at
create or replace function set_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

-- Core tables
create table if not exists commesse (
  id uuid primary key default gen_random_uuid(),
  codice text not null unique,
  anno smallint,
  numero integer,
  titolo text,
  cliente text,
  riferimento text,
  stato commessa_stato not null default 'nuova',
  stato_op text,
  priorita text check (priorita in ('bassa', 'media', 'alta', 'critica')),
  data_ingresso date,
  data_consegna_prevista date,
  data_ordine_telaio date,
  telaio_consegnato boolean not null default false,
  data_consegna_telaio_effettiva date,
  data_richiesta date,
  data_confermata date,
  ritardo text,
  conferma_cliente_preliminare3 date,
  conferma_cliente_3d_finale date,
  data_richiesta_consegna_telaio date,
  data_conferma_consegna_telaio date,
  week_consegna_telaio smallint,
  ritardo_giorni integer,
  data_arrivo_kit_cavi date,
  consegna_quadro_richiesta date,
  quote_pronte boolean,
  kit_ordinato boolean,
  arrivo_kit date,
  data_prelievo date,
  data_consegna_macchina date,
  trasporto_consegna text check (trasporto_consegna in ('van', 'ship')),
  week_ingresso_ordine smallint,
  imponibile integer,
  note_generali text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint codice_format check (codice ~ '^[0-9]{4}_[0-9]{1,3}$')
);

create table if not exists commessa_schede (
  commessa_id uuid primary key references commesse(id) on delete cascade,
  tipo_macchina text,
  num_compressori_mt integer,
  num_compressori_lt integer,
  num_compressori_aux integer,
  num_compressori_mt2_pdc_ac integer,
  num_compressori_lt2 integer,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists reparti (
  id smallint generated by default as identity primary key,
  nome text not null unique
);

create table if not exists commesse_reparti (
  commessa_id uuid not null references commesse(id) on delete cascade,
  reparto_id smallint not null references reparti(id) on delete restrict,
  stato reparto_stato not null default 'da_fare',
  note_reparto text,
  updated_at timestamptz not null default now(),
  primary key (commessa_id, reparto_id)
);

create table if not exists utenti (
  id uuid primary key references auth.users(id) on delete cascade,
  nome text,
  email text not null unique,
  ruolo ruolo_utente not null default 'viewer',
  reparto_id smallint references reparti(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists permessi_ruolo (
  ruolo ruolo_utente primary key,
  can_move_matrix boolean not null default true,
  can_delete_matrix boolean not null default true,
  can_move_gantt boolean not null default true,
  can_delete_gantt boolean not null default true,
  updated_at timestamptz not null default now()
);

create table if not exists risorse (
  id smallint generated by default as identity primary key,
  nome text not null unique,
  attiva boolean not null default true,
  utente_id uuid references utenti(id) on delete set null,
  created_at timestamptz not null default now(),
  constraint uniq_risorse_utente unique (utente_id)
);

create table if not exists assegnazioni (
  id uuid primary key default gen_random_uuid(),
  commessa_id uuid not null references commesse(id) on delete cascade,
  utente_id uuid not null references utenti(id) on delete cascade,
  ruolo ruolo_assegnazione not null default 'collaboratore',
  note text,
  created_at timestamptz not null default now(),
  constraint uniq_assegnazione unique (commessa_id, utente_id)
);

create table if not exists whitelist_email (
  email text primary key,
  ruolo_predefinito ruolo_utente not null default 'viewer',
  reparto_id_predefinito smallint references reparti(id) on delete set null,
  attiva boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists log_commessa (
  id uuid primary key default gen_random_uuid(),
  commessa_id uuid not null references commesse(id) on delete cascade,
  utente_id uuid references utenti(id) on delete set null,
  azione text not null,
  payload jsonb,
  created_at timestamptz not null default now()
);

create table if not exists attivita (
  id uuid primary key default gen_random_uuid(),
  commessa_id uuid not null references commesse(id) on delete cascade,
  titolo text not null,
  descrizione text,
  risorsa_id smallint references risorse(id) on delete set null,
  reparto_id smallint references reparti(id) on delete set null,
  assegnato_a uuid references utenti(id) on delete set null,
  stato attivita_stato not null default 'pianificata',
  data_inizio timestamptz not null,
  data_fine timestamptz not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint attivita_time_check check (data_fine >= data_inizio)
);

create table if not exists commessa_attivita_override (
  commessa_id uuid not null references commesse(id) on delete cascade,
  titolo text not null,
  stato attivita_stato not null,
  updated_at timestamptz not null default now(),
  primary key (commessa_id, titolo),
  constraint commessa_attivita_override_only_non_necessaria check (stato::text = 'non_necessaria')
);

create index if not exists idx_commessa_attivita_override_commessa on commessa_attivita_override (commessa_id);

-- Auth helpers (Supabase)
-- Returns true if the current user's email is in whitelist_email and active.
create or replace function is_whitelisted_email()
returns boolean
language sql
stable
security definer
set search_path = public, auth
as $$
  select exists (
    select 1
    from public.whitelist_email w
    where w.email = (auth.jwt() ->> 'email')
      and w.attiva = true
  );
$$;

-- Returns true if the current user is an admin.
create or replace function is_admin()
returns boolean
language sql
stable
security definer
set search_path = public, auth
as $$
  select exists (
    select 1
    from public.utenti u
    where u.id = auth.uid()
      and u.ruolo = 'admin'
  );
$$;

-- Returns true if the current user is whitelisted and not a viewer.
create or replace function can_write()
returns boolean
language sql
stable
security definer
set search_path = public, auth
as $$
  select exists (
    select 1
    from public.utenti u
    where u.id = auth.uid()
      and u.ruolo <> 'viewer'
  ) and is_whitelisted_email();
$$;

create or replace function can_manage_commesse()
returns boolean
language sql
stable
security definer
set search_path = public, auth
as $$
  select exists (
    select 1
    from public.utenti u
    where u.id = auth.uid()
      and u.ruolo in ('admin', 'responsabile')
  ) and is_whitelisted_email();
$$;

create or replace function can_manage_risorse()
returns boolean
language sql
stable
security definer
set search_path = public, auth
as $$
  select exists (
    select 1
    from public.utenti u
    where u.id = auth.uid()
      and u.ruolo in ('admin', 'responsabile')
  ) and is_whitelisted_email();
$$;

create or replace function update_commessa_planner_dates(
  p_commessa_id uuid,
  p_data_ordine_telaio date,
  p_data_consegna_macchina date,
  p_data_arrivo_kit_cavi date,
  p_data_prelievo date
)
returns void
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  v_role text;
begin
  select u.ruolo::text into v_role
  from public.utenti u
  where u.id = auth.uid();

  if v_role is null or v_role not in ('planner', 'admin', 'responsabile') then
    raise exception 'unauthorized';
  end if;

  update public.commesse
  set data_ordine_telaio = p_data_ordine_telaio,
      data_consegna_macchina = p_data_consegna_macchina,
      data_arrivo_kit_cavi = p_data_arrivo_kit_cavi,
      data_prelievo = p_data_prelievo
  where id = p_commessa_id;
end;
$$;

grant execute on function update_commessa_planner_dates(uuid, date, date, date, date) to authenticated;

create or replace function current_risorsa_id()
returns smallint
language sql
stable
security definer
set search_path = public, auth
as $$
  select r.id
  from public.risorse r
  where r.utente_id = auth.uid()
  limit 1;
$$;

create or replace function can_edit_attivita(target_risorsa_id smallint)
  returns boolean
language sql
stable
security definer
set search_path = public, auth
as $$
  select exists (
    select 1
    from public.utenti u
    where u.id = auth.uid()
      and (
        u.ruolo in ('admin', 'responsabile')
        or (u.ruolo = 'operatore' and current_risorsa_id() = target_risorsa_id)
      )
    ) and is_whitelisted_email();
  $$;

create or replace function can_edit_attivita_row(
  target_attivita_id uuid,
  target_risorsa_id smallint,
  target_assegnato_a uuid
)
returns boolean
language sql
stable
security definer
set search_path = public, auth
as $$
  select exists (
    select 1
    from public.utenti u
    where u.id = auth.uid()
      and (
        u.ruolo in ('admin', 'responsabile')
        or (
          u.ruolo = 'operatore'
          and (
            current_risorsa_id() = target_risorsa_id
            or target_assegnato_a = auth.uid()
          )
        )
      )
  ) and is_whitelisted_email();
$$;

-- On signup, create a profile if the user is whitelisted.
create or replace function handle_new_user()
returns trigger as $$
declare
  wl record;
begin
  select * into wl
  from public.whitelist_email w
  where w.email = new.email
    and w.attiva = true;

  if found then
    insert into public.utenti (id, email, ruolo, reparto_id, nome)
    values (
      new.id,
      new.email,
      wl.ruolo_predefinito,
      wl.reparto_id_predefinito,
      nullif(new.raw_user_meta_data ->> 'full_name', '')
    )
    on conflict (id) do nothing;
  end if;

  return new;
end;
$$ language plpgsql security definer set search_path = public, auth;


create index if not exists idx_attivita_commessa on attivita (commessa_id);
create index if not exists idx_attivita_periodo on attivita (data_inizio, data_fine);
create index if not exists idx_attivita_assegnato on attivita (assegnato_a);
create index if not exists idx_attivita_risorsa on attivita (risorsa_id, data_inizio, data_fine);

-- Seed reparti
insert into reparti (nome) values
  ('elettrico'),
  ('termodinamico'),
  ('cad'),
  ('tutti')
on conflict (nome) do nothing;

-- Seed risorse (modificabile)
insert into risorse (nome) values
  ('Fede'),
  ('Diego'),
  ('Riccardo'),
  ('AndreaC'),
  ('Mario'),
  ('Bruno'),
  ('Simone'),
  ('Matteo'),
  ('Denis'),
  ('Alberto'),
  ('AndreaV')
on conflict (nome) do nothing;

-- View: commesse con reparti aggregati
create or replace view v_commesse as
select
  c.id,
  c.codice,
  c.anno,
  c.numero,
  c.titolo,
  c.cliente,
  c.riferimento,
  c.stato,
  c.stato_op,
  c.priorita,
  c.data_ingresso,
  c.data_consegna_prevista,
  c.data_richiesta,
  c.data_confermata,
  c.ritardo,
  c.conferma_cliente_preliminare3,
  c.conferma_cliente_3d_finale,
  c.data_richiesta_consegna_telaio,
  c.data_conferma_consegna_telaio,
  c.week_consegna_telaio,
  c.ritardo_giorni,
  c.consegna_quadro_richiesta,
  c.quote_pronte,
  c.kit_ordinato,
  c.arrivo_kit,
  c.data_arrivo_kit_cavi,
  c.data_prelievo,
  c.data_consegna_macchina,
  c.trasporto_consegna,
  c.week_ingresso_ordine,
  c.imponibile,
  c.note_generali,
  c.created_at,
  c.updated_at,
  coalesce(
    jsonb_agg(
      jsonb_build_object(
        'reparto_id', r.id,
        'reparto_nome', r.nome,
        'stato', cr.stato,
        'note_reparto', cr.note_reparto,
        'updated_at', cr.updated_at
      )
      order by r.nome
    ) filter (where r.id is not null),
    '[]'::jsonb
  ) as reparti,
  c.data_ordine_telaio,
  c.data_arrivo_kit_cavi,
  c.telaio_consegnato,
  c.data_consegna_telaio_effettiva
from commesse c
left join commesse_reparti cr on cr.commessa_id = c.id
left join reparti r on r.id = cr.reparto_id
group by c.id;

-- Allow select on view (RLS still enforced by underlying tables)
grant select on v_commesse to authenticated;
grant select, insert, update, delete on commessa_schede to authenticated;

-- Indexes
create index if not exists idx_commesse_stato on commesse (stato);
create index if not exists idx_commesse_date on commesse (data_ingresso, data_consegna_prevista);
create index if not exists idx_commesse_consegna_macchina on commesse (data_consegna_macchina);
create index if not exists idx_commesse_ordine_telaio on commesse (data_ordine_telaio);
create index if not exists idx_commesse_anno_numero on commesse (anno, numero);
create index if not exists idx_commesse_numero on commesse (numero);
create index if not exists idx_commesse_anno on commesse (anno);
create index if not exists idx_commesse_titolo_trgm on commesse using gin (titolo gin_trgm_ops);
create index if not exists idx_commesse_reparti_stato on commesse_reparti (reparto_id, stato);
create index if not exists idx_assegnazioni_utente on assegnazioni (utente_id);

-- Triggers
drop trigger if exists trg_commesse_updated_at on commesse;
create trigger trg_commesse_updated_at
before update on commesse
for each row execute function set_updated_at();

drop trigger if exists trg_commessa_schede_updated_at on commessa_schede;
create trigger trg_commessa_schede_updated_at
before update on commessa_schede
for each row execute function set_updated_at();

drop trigger if exists trg_commesse_reparti_updated_at on commesse_reparti;
create trigger trg_commesse_reparti_updated_at
before update on commesse_reparti
for each row execute function set_updated_at();

drop trigger if exists trg_utenti_updated_at on utenti;
create trigger trg_utenti_updated_at
before update on utenti
for each row execute function set_updated_at();

drop trigger if exists trg_attivita_updated_at on attivita;
create trigger trg_attivita_updated_at
before update on attivita
for each row execute function set_updated_at();

-- Trigger on auth.users (Supabase)
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function handle_new_user();

-- RLS (Supabase)
alter table commesse enable row level security;
alter table commessa_schede enable row level security;
alter table commesse_reparti enable row level security;
alter table reparti enable row level security;
alter table risorse enable row level security;
alter table utenti enable row level security;
alter table permessi_ruolo enable row level security;
alter table assegnazioni enable row level security;
alter table whitelist_email enable row level security;
alter table log_commessa enable row level security;
alter table attivita enable row level security;
alter table commessa_attivita_override enable row level security;

-- Policies: whitelisted users can read/write operational tables
drop policy if exists commesse_select on commesse;
create policy commesse_select on commesse
  for select using (is_whitelisted_email());
drop policy if exists commesse_write on commesse;
create policy commesse_write on commesse
  for insert with check (can_manage_commesse());
create policy commesse_update on commesse
  for update using (can_manage_commesse()) with check (can_manage_commesse());
create policy commesse_delete on commesse
  for delete using (can_manage_commesse());

drop policy if exists commessa_schede_select on commessa_schede;
create policy commessa_schede_select on commessa_schede
  for select using (is_whitelisted_email());
drop policy if exists commessa_schede_write on commessa_schede;
create policy commessa_schede_write on commessa_schede
  for insert with check (can_manage_commesse());
create policy commessa_schede_update on commessa_schede
  for update using (can_manage_commesse()) with check (can_manage_commesse());
create policy commessa_schede_delete on commessa_schede
  for delete using (can_manage_commesse());

drop policy if exists commesse_reparti_select on commesse_reparti;
create policy commesse_reparti_select on commesse_reparti
  for select using (is_whitelisted_email());
drop policy if exists commesse_reparti_write on commesse_reparti;
create policy commesse_reparti_write on commesse_reparti
  for insert with check (can_manage_commesse());
create policy commesse_reparti_update on commesse_reparti
  for update using (can_manage_commesse()) with check (can_manage_commesse());
create policy commesse_reparti_delete on commesse_reparti
  for delete using (can_manage_commesse());

drop policy if exists reparti_select on reparti;
create policy reparti_select on reparti
  for select using (is_whitelisted_email());
drop policy if exists reparti_write on reparti;
create policy reparti_write on reparti
  for insert with check (can_manage_risorse());
create policy reparti_update on reparti
  for update using (can_manage_risorse()) with check (can_manage_risorse());
create policy reparti_delete on reparti
  for delete using (can_manage_risorse());

drop policy if exists risorse_select on risorse;
create policy risorse_select on risorse
  for select using (is_whitelisted_email());
drop policy if exists risorse_write on risorse;
create policy risorse_write on risorse
  for insert with check (can_manage_risorse());
create policy risorse_update on risorse
  for update using (can_manage_risorse()) with check (can_manage_risorse());
create policy risorse_delete on risorse
  for delete using (can_manage_risorse());

drop policy if exists utenti_select on utenti;
create policy utenti_select on utenti
  for select using (is_whitelisted_email());
drop policy if exists utenti_write on utenti;
create policy utenti_write on utenti
  for insert with check (can_manage_risorse());
create policy utenti_update on utenti
  for update using (can_manage_risorse()) with check (can_manage_risorse());
create policy utenti_delete on utenti
  for delete using (can_manage_risorse());

drop policy if exists permessi_ruolo_select on permessi_ruolo;
create policy permessi_ruolo_select on permessi_ruolo
  for select using (is_whitelisted_email());
drop policy if exists permessi_ruolo_admin_write on permessi_ruolo;
create policy permessi_ruolo_admin_write on permessi_ruolo
  for insert with check (is_admin());
create policy permessi_ruolo_admin_update on permessi_ruolo
  for update using (is_admin()) with check (is_admin());
create policy permessi_ruolo_admin_delete on permessi_ruolo
  for delete using (is_admin());

drop policy if exists assegnazioni_select on assegnazioni;
create policy assegnazioni_select on assegnazioni
  for select using (is_whitelisted_email());
drop policy if exists assegnazioni_write on assegnazioni;
create policy assegnazioni_write on assegnazioni
  for insert with check (can_manage_commesse());
create policy assegnazioni_update on assegnazioni
  for update using (can_manage_commesse()) with check (can_manage_commesse());
create policy assegnazioni_delete on assegnazioni
  for delete using (can_manage_commesse());

drop policy if exists log_commessa_select on log_commessa;
create policy log_commessa_select on log_commessa
  for select using (is_whitelisted_email());
drop policy if exists log_commessa_write on log_commessa;
create policy log_commessa_write on log_commessa
  for insert with check (can_write());
create policy log_commessa_update on log_commessa
  for update using (can_write()) with check (can_write());
create policy log_commessa_delete on log_commessa
  for delete using (can_write());

drop policy if exists attivita_select on attivita;
create policy attivita_select on attivita
  for select using (is_whitelisted_email());
drop policy if exists attivita_write on attivita;
create policy attivita_write on attivita
  for insert with check (can_edit_attivita(risorsa_id));
create policy attivita_update on attivita
  for update using (can_edit_attivita_row(id, risorsa_id, assegnato_a))
    with check (can_edit_attivita_row(id, risorsa_id, assegnato_a));
create policy attivita_delete on attivita
  for delete using (can_edit_attivita_row(id, risorsa_id, assegnato_a));

drop policy if exists commessa_attivita_override_select on commessa_attivita_override;
create policy commessa_attivita_override_select on commessa_attivita_override
  for select using (is_whitelisted_email());
drop policy if exists commessa_attivita_override_write on commessa_attivita_override;
create policy commessa_attivita_override_write on commessa_attivita_override
  for insert with check (can_write());
create policy commessa_attivita_override_update on commessa_attivita_override
  for update using (can_write()) with check (can_write());
create policy commessa_attivita_override_delete on commessa_attivita_override
  for delete using (can_write());

-- Policies: whitelist management is admin-only (readable by whitelisted)
drop policy if exists whitelist_select on whitelist_email;
create policy whitelist_select on whitelist_email
  for select using (is_whitelisted_email());

drop policy if exists whitelist_admin_write on whitelist_email;
create policy whitelist_admin_write on whitelist_email
  for insert with check (is_admin());
create policy whitelist_admin_update on whitelist_email
  for update using (is_admin()) with check (is_admin());
create policy whitelist_admin_delete on whitelist_email
  for delete using (is_admin());

-- Example seed (optional, safe to keep with on conflict)
insert into commesse (
  codice, titolo, cliente, stato, priorita, data_ingresso, data_consegna_prevista, note_generali
) values (
  '2026_001', 'Commessa esempio', 'Cliente demo', 'nuova', 'media', current_date, current_date + interval '30 days', 'Esempio di commessa'
) on conflict (codice) do nothing;

insert into permessi_ruolo (ruolo, can_move_matrix, can_delete_matrix, can_move_gantt, can_delete_gantt)
values
  ('admin', true, true, true, true),
  ('responsabile', true, true, true, true),
  ('planner', false, false, true, false),
  ('operatore', false, false, false, false),
  ('viewer', false, false, false, false)
on conflict (ruolo) do nothing;

insert into commesse_reparti (commessa_id, reparto_id, stato)
select c.id, r.id, 'da_fare'
from commesse c
join reparti r on r.nome in ('elettrico', 'cad')
where c.codice = '2026_001'
on conflict (commessa_id, reparto_id) do nothing;

-- Seed activity example
insert into attivita (
  commessa_id, titolo, descrizione, reparto_id, stato, data_inizio, data_fine
)
select
  c.id,
  'Kickoff commessa',
  'Attivita iniziale di coordinamento',
  r.id,
  'pianificata',
  now(),
  now() + interval '2 hours'
from commesse c
join reparti r on r.nome = 'tutti'
where c.codice = '2026_001'
on conflict do nothing;
